# Copyright Jacob Wujciak-Jens
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Images supporting multiple platforms (architectures) used to require
# Quemu due to the limited runners available in GitHub Actions but
# now arm64 runners are available and should work much faster than with emulation
#
# Notes:
# It's possible to add multiple caches of the same time but only the last one
# will actually be used.

name: Docker Multi-Platform Image

on:
  push:
    paths:
      - .github/workflows/docker-multi-platform.yml
  workflow_dispatch: {}

permissions: {}

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.dockerfile.outputs.content }}
    steps:
      - name: Create Dockerfile
        id: dockerfile
        run: |
          DOCKERFILE=$(cat << 'EOL'
          # Base image
          FROM ubuntu:20.04 AS base
          RUN apt-get update && apt-get upgrade -y

          # Stage 1
          FROM base AS stage1
          RUN apt-get install -y curl wget
          EOL
          )
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$DOCKERFILE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  emulation:
    needs: dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Save Dockerfile
        env:
          DOCKERFILE_CONTENT: ${{ needs.dockerfile.outputs.dockerfile }}
        run: |
          echo "$DOCKERFILE_CONTENT" > Dockerfile

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Base Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          target: stage1
          tags: stage1:latest
          push: false
          load: true

      - name: Inspect Result
        run: |
          docker image ls
          docker inspect stage1:latest

  native:
    needs: dockerfile
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            platform: arm64
          - runner: ubuntu-24.04
            platform: amd64

    steps:
      - name: Save Dockerfile
        env:
          DOCKERFILE_CONTENT: ${{ needs.dockerfile.outputs.dockerfile }}
        run: |
          echo "$DOCKERFILE_CONTENT" > Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Base Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: stage1
          tags: stage1-${{ matrix.platform }}:latest
          load: true
          push: false

      - name: Export Image
        env:
          ARCH: ${{ matrix.platform }}
        run: |
          docker save -o $arch.tar stage1-$ARCH:latest
      - name: Upload Docker Cache
        uses: actions/upload-artifact@v4
        with:
          name: stage1-${{ matrix.platform }}
          path: ${{ matrix.platform }}.tar
          retention-days: 5

  combine:
    needs: [native, dockerfile]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get Native Caches
        uses: actions/download-artifact@v4
        with:
          pattern: stage1-*
          merge-multiple: true

      - name: Merge Images
        run: |
          docker load arm64.tar
          docker load amd64.tar

          docker buildx imagetools create -t stage1:latest stage1-arm64:latest stage1-amd64:latest

          docker buildx imagetools inspect stage1:latest
